### ISSUE TITLE
Start-Up Error - EACCES denied Synology

### ISSUE THREAD

**Issue by BAngel87** [benzman81/homebridge-nukiio#24]
Hey benzman81, nice work on Nuki Integration,

sadly I'am not able to get it working on my Homebridge running as ane Installation with Docker on my Synology NAS.

Config:
"platforms": [
{
"platform": "NukiBridge",
"bridge_url": "192.168.178.14",
"api_token" : "uaaaaa",
"request_timeout_lockstate": 5000,
"request_timeout_lockaction": 30000,
"cache_directory": "./.node-persist/storage",
"webhook_server_ip_or_name": "192.168.178.27",
"webhook_port": 51827,
"lock_state_mode": 1,
"add_maintainance_buttons": false,
"locks": [
{
"id": "10159753",
"name": "Haustur",
"usesDoorLatch" : true,
"priority" : 1
}
]
}
]

Error:
2018-05-04 05:24:43stdout-U /homebridge -P /homebridge/node_modules 2018-05-04 05:24:37stdout at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36) 2018-05-04 05:24:37stdout at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:304:32) 2018-05-04 05:24:37stdout at new NukiBridgePlatform (/homebridge/node_modules/homebridge-nukiio/index.js:17:23) 2018-05-04 05:24:37stdout at new NukiBridge (/homebridge/node_modules/homebridge-nukiio/nukibridge.js:70:18) 2018-05-04 05:24:37stdout at Object.nodePersist.initSync (/homebridge/node_modules/node-persist/src/node-persist.js:37:32) 2018-05-04 05:24:37stdout at LocalStorage.initSync (/homebridge/node_modules/node-persist/src/local-storage.js:141:14) 2018-05-04 05:24:37stdout at LocalStorage.parseStorageDirSync (/homebridge/node_modules/node-persist/src/local-storage.js:600:20) 2018-05-04 05:24:37stdout at Function.sync (/homebridge/node_modules/mkdirp/index.js:77:24) 2018-05-04 05:24:37stdout at sync (/homebridge/node_modules/mkdirp/index.js:71:13) 2018-05-04 05:24:37stdout at Object.fs.mkdirSync (fs.js:885:18) 2018-05-04 05:24:37stdoutError: EACCES: permission denied, mkdir '/run/s6/services/homebridge/.node-persist' 2018-05-04 05:24:37stdout2018-05-04 05:24:37stdout ^ 2018-05-04 05:24:37stdout throw err0; 2018-05-04 05:24:37stdout/homebridge/node_modules/mkdirp/index.js:90 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] [NukiBridge] Initializing Nuki bridge 'http://192.168.178.144'... 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] [NukiBridge] Initializing NukiBridge platform... 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] Loading 1 platforms... 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] --- 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] Loaded config.json with 0 accessories and 1 platforms. 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] --- 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch' 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] Registering accessory 'homebridge-nukiio.NukiLock' 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] Registering platform 'homebridge-nukiio.NukiBridge' 2018-05-04 05:24:37stdout[2018-5-4 05:24:37] Loaded plugin: homebridge-nukiio

I Allready tried:
- deleting "cache_directory": "./.node-persist/storage", in Config
- deleting all files in Persist

I would love to hear from you :-)

Thanks in advance,... BAngel

**Comment by benzman81** [comment]
This shows, that you have no permission to access /run/s6/services/homebridge/.node-persist.
You should point the json config property "cache_directory" to a directory where the user running homebridge has access to, i.e. /home/myuser/.node-persist

**Comment by Domme86** [comment]
Sorry for interupting again, but I'm unable to manage it because I do not know which path I have to take for the example aboth. I already thried "/home.homebridge/.node-persist" but did not work. Could you please support?

**Comment by benzman81** [comment]
I can not tell you anything more than to set the cache dir to a folder that exists and you have access to.
