### ISSUE TITLE
Can't start the plugin

### ISSUE THREAD

**Issue by DarKOrange75** [benzman81/homebridge-nukiio#27]
Hi,

I installed Homebridge and your plugin on a Synology NAS using Docker but I can't start Homebridge if I call your plugin in the configuration file. Here is the error I get, please help :-)

[NukiBridge] Initializing NukiBridge platform...
[2018-6-27 18:28:50] [NukiBridge] Initializing Nuki bridge 'http://192.168.1.12'...
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/cache'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/homebridge/node_modules/mkdirp/index.js:71:13)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/node-persist.js:37:32)
    at new NukiBridge (/homebridge/node_modules/homebridge-nukiio/nukibridge.js:70:16)
    at new NukiBridgePlatform (/homebridge/node_modules/homebridge-nukiio/index.js:17:23)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:325:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by DarKOrange75** [comment]
Here is my configuration file:

{
            "platform": "NukiBridge",
            "bridge_url": "xxxxxxxxx",
            "api_token": "xxxxxxx",
            "request_timeout_lockstate": 5000,
            "request_timeout_lockaction": 30000,
            "cache_directory": "./cache",
            "webhook_server_ip_or_name": "xxxxxxxx",
            "webhook_port": 51827,
            "lock_state_mode": 0,
            "add_maintainance_buttons": false,
            "locks": [
                {
                    "id": "xxxxxxx",
                    "name": "Porte d'entrée",
                    "usesDoorLatch": true,
                    "priority": 1
                }
            ]
        }

**Comment by DarKOrange75** [comment]
I get the same error if I leave the default parameter for "cache_directory"

[2018-6-27 18:39:48] [NukiBridge] Initializing NukiBridge platform...
[2018-6-27 18:39:48] [NukiBridge] Initializing Nuki bridge 'http://192.168.1.12'...
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/.node-persist'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/homebridge/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/homebridge/node_modules/mkdirp/index.js:77:24)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/node-persist.js:37:32)
    at new NukiBridge (/homebridge/node_modules/homebridge-nukiio/nukibridge.js:70:16)
    at new NukiBridgePlatform (/homebridge/node_modules/homebridge-nukiio/index.js:17:23)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:325:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by benzman81** [comment]
You need to assign a folder where the service has access to.

**Comment by benzman81** [comment]
I use this image and it worls lika a charm: https://github.com/marcoraddatz/homebridge-docker

**Comment by DarKOrange75** [comment]
Thank you for your fast answer :-) I'll try that.

**Comment by DarKOrange75** [comment]
OK I assigned a folder with the right permissions, the plugin is now working.
But I have a door with a latch and the button that is supposed to unlock the door without pulling the latch is actually pulling it.

**Comment by DarKOrange75** [comment]
Well creating the folder by myself was a temporary fix. I had to restart the container, the folder is gone and the plugin is not working anymore.

There might be something wrong with the plugin or I am missing something.

here is the cache folder config:

"cache_directory": "./cache/storage"

and here is the result:

Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/cache'

Why is the plugin adding "/run/s6/services/homebridge" to the path and deleting everything after "./cache/" ?

**Comment by benzman81** [comment]
Your docker image runs HB as a service and uses this directiry to run HB. If you recreate an image of docker, than everythin on it is gone except stuff in its mounted volumes.

**Comment by benzman81** [comment]
You need to choose a folder where HB has access to.

**Comment by DarKOrange75** [comment]
OK I figured out how to correctly enter the path to this folder. Thank you for your explanations. Everything is working fine now except for the button supposed to unlock without pulling the latch which is actually pulling the latch.

**Comment by benzman81** [comment]
Great, have fun.

**Comment by aesthetiker** [comment]
Can you tell me what is the right syntax for the folder? and how you set the permissions? Thanks

**Comment by benzman81** [comment]
@aesthetiker the syntax is a relative path like "../foo/bar" or a fully qualified path from root like "/foo/bar".
Setting permissions can be done with the command chmod (see unix documentation).

**Comment by aesthetiker** [comment]
I created a folder /home/homebridge/cache and tried sudo chmod -R 777 /home/homebridge/cache still this error: 

Error: EACCES: permission denied, mkdir '/home/homebridge/cache'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/homebridge/node_modules/mkdir

I used the .spk package for my synology NAS

**Comment by benzman81** [comment]
@aesthetiker no clue on that. If you do 777 it definetly should work and all other users that had this problem solved it that way.

**Comment by DarKOrange75** [comment]
@aesthetiker what is your setup? Are you using Docker on a NAS ?

**Comment by aesthetiker** [comment]
Yes i am using .spk package for my synology NAS but this is running i as a Docker container.

**Comment by DarKOrange75** [comment]
Then if you followed the default installation you should find a "docker" folder on your volume and inside that folder a "homebridge" folder with all the plugins inside (this is the volume mounted in docker if you followed the default installation). Create a folder in that folder or any subfolder and give 777 permissions to that folder. Then your path should be something like this:

"cache_directory": "/homebridge/myfolder"
