### ISSUE TITLE
homebridge start doesen't work

### ISSUE THREAD

**Issue by neonightmare** [benzman81/homebridge-nukiio#3]
Hi.
got this error:

`[Werkstatt-Türe] Initializing Nuki accessory...
[Werkstatt-Türe] Initializing Nuki bridge...
/usr/local/lib/node_modules/homebridge-nukiio/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/var/log/.node-persist.'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at sync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/mkdirp/index.js:77:24)
    at Object.LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:559:20)
    at Object.LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:143:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/node-persist.js:37:32)
    at Object.__dirname.init (/usr/local/lib/node_modules/homebridge-nukiio/nukibridge.js:45:13)
    at new NukiAccessory (/usr/local/lib/node_modules/homebridge-nukiio/index.js:28:16)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:244:29)
pi@raspberrypi /var/log $ `

got this in my conf:

`{
        "accessory": "Nuki",
        "bridge_url": "192.168.1.101",
        "name": "Door1",
        "lock_id"  : "myID",
        "api_token" : "myAPItoken",
        "lock_action" : "2",
        "unlock_action" : "1",
        "request_timeout_lockstate":5000,
        "request_timeout_lockaction": 30000,
        "cache_directory": "./.node-persist./storage",
        "webhook_server_port": 51827
        },`

ID and Token from the app..

any idea?
THX

**Comment by benzman81** [comment]
Hi,

this is clearly a permission problem. You can fix this by using a differen path for "cache_directory" where the user has permission, or you can create the Folder "/var/log/.node-persist" by hand and give it the needed rw permission via chmod.

Regards,
Markus

**Comment by neonightmare** [comment]
Big THX, works now!

Will test the look in the evening...

regards
neo
