### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/.node-persist'

### ISSUE THREAD

**Issue by tonio-29** [benzman81/homebridge-nukiio#31]
Hello
I have a problem : 
My Log : 
[2018-9-22 21:47:09] [NukiBridge] Initializing NukiBridge platform...
[2018-9-22 21:47:09] [NukiBridge] Initializing Nuki bridge 'http://192.168.1.48:8080'...
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/.node-persist'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/homebridge/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/homebridge/node_modules/mkdirp/index.js:77:24)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/homebridge-nukiio/node_modules/node-persist/src/node-persist.js:37:32)
    at new NukiBridge (/homebridge/node_modules/homebridge-nukiio/nukibridge.js:70:16)
    at new NukiBridgePlatform (/homebridge/node_modules/homebridge-nukiio/index.js:17:23)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:326:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
[2018-9-22 21:47:11] [homebridge-config-ui-x] Homebridge restart request received
[2018-9-22 21:47:11] [homebridge-config-ui-x] Executing restart command: killall -9 homebridge && killall -9 homebridge-config-ui-x
[2018-9-22 21:47:11] [homebridge-config-ui-x] Restart command exited with an error. Failed to restart Homebridge.

My Conf : 

		    {
            "platform": "NukiBridge",
            "bridge_url": "http://192.168.XX.XX:8080",
            "api_token": "XXXXXX",
            "request_timeout_lockstate": 5000,
            "request_timeout_lockaction": 30000,
            "cache_directory": "./.node-persist/storage",
            "webhook_server_ip_or_name": "xxx.xxx.xxx.xxx",
            "webhook_port": 51827,
            "lock_state_mode": 0,
            "add_maintainance_buttons": false,
            "locks": [
                {
                    "id": "XXXXX",
                    "name": "My Door",
                    "usesDoorLatch": false,
                    "priority": 1
                }
            ]
        }

No poblem witch another plugin (Nest...)

Can You help me?
Thanks

**Comment by benzman81** [comment]
See #24 and #27

**Comment by tonio-29** [comment]
Thank's
It's OK now !
