### ISSUE TITLE
homebridge crash - nukibridge ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by nicoh88** [benzman81/homebridge-nukiio#47]
Hi Markus,

wenn die Nuki Bridge aus irgendwelchen Gründen, beim Homebridge Start/Neustart nicht erreichbar ist oder `HTTP 503 Unavailable`, dann stürzt die Homebridge-Instanz direkt wieder ab und alle anderen Plugins werden nicht gestartet.

```
Jul 19 09:40:46 frida homebridge[21157]: [2019-7-19 09:40:46] [NukiBridge] Send request to Nuki bridge 'http://192.168.137.67:8080' on '/callback/list' with '{"token":"ABCDEF"}'.
Jul 19 09:40:46 frida homebridge[21157]: [2019-7-19 09:40:46] [NukiBridge] Request to Nuki bridge 'http://192.168.137.67:8080' finished with status code '200' and body '{"callbacks": []}'. null
Jul 19 09:40:46 frida homebridge[21157]: [2019-7-19 09:40:46] [NukiBridge] Send request to Nuki bridge 'http://192.168.137.67:8080' on '/callback/add' with '{"token":"ABCDEF","url":"http://192.168.137.10:54321/"}'.
Jul 19 09:40:51 frida homebridge[21157]: [2019-7-19 09:40:51] [NukiBridge] Request to Nuki bridge 'http://192.168.137.67:8080' finished with status code '-1' and body 'undefined'. Error: ESOCKETTIMEDOUT
Jul 19 09:40:51 frida homebridge[21157]:     at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:812:19)
Jul 19 09:40:51 frida homebridge[21157]:     at Object.onceWrapper (events.js:288:20)
Jul 19 09:40:51 frida homebridge[21157]:     at ClientRequest.emit (events.js:200:13)
Jul 19 09:40:51 frida homebridge[21157]:     at Socket.emitRequestTimeout (_http_client.js:675:40)
Jul 19 09:40:51 frida homebridge[21157]:     at Object.onceWrapper (events.js:288:20)
Jul 19 09:40:51 frida homebridge[21157]:     at Socket.emit (events.js:200:13)
Jul 19 09:40:51 frida homebridge[21157]:     at Socket._onTimeout (net.js:432:8)
Jul 19 09:40:51 frida homebridge[21157]:     at listOnTimeout (internal/timers.js:531:17)
Jul 19 09:40:51 frida homebridge[21157]:     at processTimers (internal/timers.js:475:7) {
Jul 19 09:40:51 frida homebridge[21157]:   code: 'ESOCKETTIMEDOUT',
Jul 19 09:40:51 frida homebridge[21157]:   connect: false
Jul 19 09:40:51 frida homebridge[21157]: }
Jul 19 09:40:51 frida homebridge[21157]: [2019-7-19 09:40:51] Error: Adding webhook failed: Error: ESOCKETTIMEDOUT
Jul 19 09:40:51 frida homebridge[21157]:     at NukiBridge.<anonymous> (/usr/lib/node_modules/homebridge-nukiio/nukibridge.js:189:15)
Jul 19 09:40:51 frida homebridge[21157]:     at NukiBridge.<anonymous> (/usr/lib/node_modules/homebridge-nukiio/nukibridge.js:396:7)
Jul 19 09:40:51 frida homebridge[21157]:     at self.callback (/usr/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:185:22)
Jul 19 09:40:51 frida homebridge[21157]:     at Request.emit (events.js:200:13)
Jul 19 09:40:51 frida homebridge[21157]:     at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:815:16)
Jul 19 09:40:51 frida homebridge[21157]:     at Object.onceWrapper (events.js:288:20)
Jul 19 09:40:51 frida homebridge[21157]:     at ClientRequest.emit (events.js:200:13)
Jul 19 09:40:51 frida homebridge[21157]:     at Socket.emitRequestTimeout (_http_client.js:675:40)
Jul 19 09:40:51 frida homebridge[21157]:     at Object.onceWrapper (events.js:288:20)
Jul 19 09:40:51 frida homebridge[21157]:     at Socket.emit (events.js:200:13)
Jul 19 09:40:51 frida homebridge[21157]: [2019-7-19 09:40:51] Got SIGTERM, shutting down Homebridge...
```

Wäre cool, wenn du das Abfangen könntest, damit dennoch die restlichen Homebridge Plugins weiterlaufen und Homebridge nicht abstürzt.

Gruß Nico

---

**BTW:** Ping geht. Port 8080 ist offen. API abfragen werden mit `HTTP 503 Unavailable` beantwortet. Vermutlich ist auf der Bridge ein `fail2ban` oder ähnliches konfiguriert und er hat mich, als ich vorhin ein Fehler in der `config.json` hatte und er somit alle 10 Sekunden versucht hat eine Verbindung aufzubauen, gesperrt. Strom ziehen hat nichts gebracht. Jetzt heißt es warten...

```
{
      "platform": "NukiBridge",
      "bridge_url": "http://192.168.137.67:8080",
      "api_token" : "yA6Uzv",
      "request_timeout_lockstate": 5000,
      "request_timeout_lockaction": 30000,
      "cache_directory": "/var/lib/homebridge5/.homebridge-nukiio/node-persist",
      "lock_state_mode": 0,
      "add_maintainance_buttons": false,
      "webhook_server_ip_or_name": "192.168.137.10",
      "webhook_port": 51234,
      "locks": [
        {
          "id": "0123456789",
          "name": "Haustür",
          "usesDoorLatch" : true,
          "priority" : 1
        }
      ]
    }
```
---

**UPDATE_2019-07-19_13-44:**

Hmm, jetzt funktionieren die API abfragen wieder, aber ich bekomme noch immer den `ESOCKETTIMEDOUT`. **WTF!**

---

**UPDATE_2019-07-19_14-23:**

Scheint am `callback/add` Kommando deines Plugins zu liegen. Habe die URL jetzt manuell gesetzt:

`curl http://192.168.137.67:8080/callback/add?url=http%3A%2F%2F192.168.137.10%3A51234%2F\&token=ABCDEF`

Im Homebridge Log erscheint nun wie von mir geplant `Webhook for plugin already exists.`.

@benzman81: Dennoch scheint da beim `callback/add` irgendetwas schief zu laufen

**Comment by benzman81** [comment]
Hmm, da sollte kein problem sein, läuft bei mir seit Ewigkeiten stabil.

Das mit dem start kann ich schlecht ändern, ist bei viele plugins so. Bei meinem ist es, weil ich den initialen status live ermitteln will und einen callback Aden muss, wenn gewünscht. Später leider nicht möglich, außer man wollt regelmäßig die bridge auf Verfügbarkeit, aber polling ist immer schlecht.
