### ISSUE TITLE
Plugin not starting

### ISSUE THREAD

**Issue by Rudi6** [benzman81/homebridge-nukiio#54]
Hello,

Installed Hoobs on RaspPI with lastest updates but cannot get the plugin to start
All other pllugins (Homebridge Config UI X and Homebridge Homeseer Plugin 2018) fail to start also if add the configuration below to cofig.json
No idea how to troubleshoot, sorry

`		{
			"platform": "NukiBridge",
			"bridge_url": "192.168.2.42:8080",
			"api_token" : "9pXB0j",
			"request_timeout_lockstate": 30000,
			"request_timeout_lockaction": 60000,
			"request_timeout_other": 30000,
			"cache_directory": "./.node-persist/storage",
			"webhook_server_ip_or_name": "192.168.2.55",
			"webhook_port": 51234,
			"lock_state_mode": 0,
			"lockaction_maxtries": 3,
			"lockaction_retrydelay": 3000,
			"add_maintainance_buttons": false,
			"locks": [
				{
					"id": "307306921",
					"name": "Tuindeur",
					"usesDoorLatch" : false,
					"priority" : 1
				}
			]
		}`

**Comment by benzman81** [comment]
What information is in the log.

**Comment by Rudi6** [comment]
With log are U referring too (basic raspPI user)

**Comment by Rudi6** [comment]
`[12/9/2019, 8:03:27 PM] Registering accessory 'homebridge-nukiio.NukiLock'
[12/9/2019, 8:03:27 PM] Registering accessory 'homebridge-nukiio.NukiOpener'
[12/9/2019, 8:03:27 PM] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch'
[12/9/2019, 8:03:27 PM] ---
[12/9/2019, 8:03:27 PM] Loading 2 platforms...
[12/9/2019, 8:03:27 PM] [Config] Initializing config platform...
[12/9/2019, 8:03:27 PM] [Config] Running in Standalone Mode.
[12/9/2019, 8:03:27 PM] [NukiBridge] Initializing NukiBridge platform...
[12/9/2019, 8:03:27 PM] [NukiBridge] Initializing Nuki bridge 'http://192.168.2.42:8080'...
[12/9/2019, 8:03:27 PM] Error: EACCES: permission denied, mkdir '/.node-persist'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/mkdirp/index.js:77:24)
    at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/node-persist.js:37:32)
    at new NukiBridge (/usr/local/lib/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:48:16)
    at new NukiBridgePlatform (/usr/local/lib/node_modules/homebridge-nukiio/src/homekit/NukiBridgePlatform.js:16:21)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
[12/9/2019, 8:03:27 PM] Got SIGTERM, shutting down Homebridge...
h`

**Comment by benzman81** [comment]
The homebridge log. I dont own a raspi so have have to figure out where it is.

**Comment by Rudi6** [comment]
EACCES: permission denied, mkdir '/.node-persist' at Object.mkdirSync
Looks like the makedir command fails
Any suggestions whre to point this one to

**Comment by benzman81** [comment]
You have to change the cache dir to a writeable directory. See #24 and #27

**Comment by Rudi6** [comment]
Will try to find a suitable dir for it, thz for your support
