### ISSUE TITLE
Homebridge issue on startup

### ISSUE THREAD

**Issue by VooklejFilip** [benzman81/homebridge-nukiio#58]
Hi,

after installing homebridge-nukiio i entered all the required setting and than reboot homebridge. But than i got this error and it goes on and on, always restarting homebridge.  I didn't change anything in the configuration, just used the configuration page in plugins. Could you please take a look?

Thanks

[7/7/2020, 18:35:06] Loaded plugin: homebridge-nukiio@0.13.0
[7/7/2020, 18:35:06] Registering platform 'homebridge-nukiio.NukiBridge'
[7/7/2020, 18:35:06] Registering accessory 'homebridge-nukiio.NukiLock'
[7/7/2020, 18:35:06] Registering accessory 'homebridge-nukiio.NukiOpener'
[7/7/2020, 18:35:06] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch'
[7/7/2020, 18:35:06] ---
[7/7/2020, 18:35:07] Loaded plugin: homebridge-xiaomi-roborock-vacuum@0.12.0
[7/7/2020, 18:35:07] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
[7/7/2020, 18:35:07] ---
[7/7/2020, 18:35:07] Loading 2 platforms...
[7/7/2020, 18:35:07] [Config] Initializing config platform...
[7/7/2020, 18:35:07] [Config] Running in Service Mode
[7/7/2020, 18:35:07] Error loading platform requested in your config.json at position 2
[7/7/2020, 18:35:07] Error: The requested platform 'homebridge-nukiio' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[7/7/2020, 18:35:07] Got SIGTERM, shutting down Homebridge...

Here is my configuration:

{
    "bridge": {
        "name": "Homebridge 1F9C",
        "username": "0E:BA:92:A5:1F:9C",
        "port": 51738,
        "pin": "504-17-951"
    },
    "accessories": [
        {
            "name": "Robootrok",
            "ip": "192.168.1.112",
            "token": "41755464655a316e6f6b4c41326c644c",
            "waterBox": false,
            "pause": true,
            "dock": true,
            "delay": false,
            "cleanword": "clean",
            "autoroom": true,
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "bridge_url": "http://192.168.1.210:8080",
            "api_token": "OvG06L",
            "lock_state_mode": 0,
            "webhook_port": 51827,
            "cache_directory": "./.node-persist/storage",
            "request_timeout_lockstate": 15000,
            "request_timeout_lockaction": 45000,
            "request_timeout_other": 15000,
            "lockaction_maxtries": 3,
            "lockaction_retrydelay": 3000,
            "add_maintainance_buttons": false,
            "locks": [
                {
                    "id": "1DF7124",
                    "name": "Door lock",
                    "usesDoorLatch": true,
                    "usesDoorContactSensor": false,
                    "priority": 99
                }
            ],
            "platform": "homebridge-nukiio"
        }
    ]
}

**Comment by benzman81** [comment]
Sorry for the hassle. I just added the config ui stuff a couple of days ago. There was an issue in the naming. Fixed with 0.13.1.
