### ISSUE TITLE
Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by leendersf** [benzman81/homebridge-nukiio#59]
Hello, it works. A little bit.. But I get tthis message:

[7/22/2020, 2:24:13 PM] [NukiBridge] Send request to Nuki bridge 'http://10.0.1.59:7777' on '/lockState' with '{"token":"Z4eU95","nukiId":"346414421","deviceType":0}'.
[7/22/2020, 2:24:28 PM] [NukiBridge] Request to Nuki bridge 'http://10.0.1.59:7777' finished with status code '-1' and body 'undefined'. Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-nukiio/node_modules/request/request.js:812:19)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at Socket.emitRequestTimeout (_http_client.js:709:9)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}

Already tried changing the default port to 7777. Any ideas? Thanks in advance!

**Comment by benzman81** [comment]
Looks like the request does not work due to socket timeout. You can check if helps to change the request timeouts according to readme. I think someone had this issue if the bridge could not connect to the lock properly. He repositioned the bridge, then it worked.

**Comment by leendersf** [comment]
I think that was it!!! Thank you very much!!

**Comment by benzman81** [comment]
What did youd do exactly to fix this?

**Comment by leendersf** [comment]
I changed the timeouts: exactly like in the readme. Everything runs perfectly! Thank you for the quick support!

The only thing I am getting is this:

[NukiBridge] Request to Nuki bridge 'http://10.0.1.59:7777' finished with status code '-1' and body 'undefined'. Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-nukiio/node_modules/request/request.js:812:19)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at Socket.emitRequestTimeout (_http_client.js:709:9)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}

But this is normal? Or not. Keep up the good work!

**Comment by benzman81** [comment]
There should be no error.

**Comment by leendersf** [comment]
Ok.. This is my config:

 {
            "bridge_url": "http://10.0.1.59:7777",
            "api_token": "xxxxxxx",
            "lock_state_mode": 0,
            "webhook_port": 51827,
            "request_timeout_lockstate": 30000,
            "request_timeout_lockaction": 60000,
            "request_timeout_other": 30000,
            "lockaction_maxtries": 3,
            "lockaction_retrydelay": 3000,
            "add_maintainance_buttons": false,
            "locks": [
                {
                    "id": "1111111111",
                    "name": "Nuki"
                }
            ],
            "platform": "NukiBridge"
        }

**Comment by benzman81** [comment]
Does it work sometimes, or never? Can you open `http://10.0.1.59:7777/info?token=yourtoken` in browser?

**Comment by benzman81** [comment]
btw change your config to hide id and token ;-)

**Comment by leendersf** [comment]
I get this: [{"deviceType": 0, "nukiId": 346414421, "name": "Nuki"}]

And it opens and closes most of the times. But it takes a long time, not instant. Further: my Bridge firmware is 2.3.0. It struggles: like when I want to force a firmware update and I load the plugin with the maintainance buttons I see the buttons but I cannot seem to make it update. My bridge is 3 days old now.

Oh, that was nog my actual token btw ;-)

**Comment by leendersf** [comment]
Error at this moment after resetting the bridge:

[7/22/2020, 6:03:08 PM] [NukiBridge] Request to Nuki bridge 'http://10.0.1.59:7777' finished with status code '-1' and body 'undefined'. Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-nukiio/node_modules/request/request.js:812:19)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at Socket.emitRequestTimeout (_http_client.js:709:9)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}

**Comment by leendersf** [comment]
And I am now doing http://10.0.1.59:7777/fwupdate?token=MYTOKEN To force a firmwareupgrade. The screen stays white. I think i have to wait untill it is finished..

**Comment by leendersf** [comment]
This has become an adventure ;-)

My bridge slept for a night and is now on firmware 2.6.0. As far as I can see no more errors. Also: the maintainance buttons don't give errors anymore.

I will close this thread. Thanks a lot for your help!!

**Comment by benzman81** [comment]
Great!
