### ISSUE TITLE
finished with status code '-1' and body 'undefined'

### ISSUE THREAD

**Issue by kingwings81** [benzman81/homebridge-nukiio#6]
Hi, i always end up with this error message: 

[2016-10-05 11:50:38] Homebridge is running on port 51826.
[2016-10-05 11:50:39] Send request to Nuki bridge '192.168.X.XXX:8080' on '/lockState' with '{"token":"XXXXX","nukiId":"XXXXXXX"}'.
[2016-10-05 11:50:39] Request to Nuki bridge '192.168.X.XXX:8080' finished with status code '-1' and body 'undefined'. Error: Invalid protocol: 192.168.X.XXX:
    at Request.init (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:619:31)
    at new Request (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:283:8)
    at request (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/index.js:50:10)
    at Function.request.get (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/index.js:63:27)
    at NukiBridge._sendRequest (/usr/local/lib/node_modules/homebridge-nukiio/nukibridge.js:252:13)
    at NukiBridge.lockState (/usr/local/lib/node_modules/homebridge-nukiio/nukibridge.js:222:14)
    at NukiBridge._processNextQueueEntry (/usr/local/lib/node_modules/homebridge-nukiio/nukibridge.js:343:22)
    at NukiBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/nukibridge.js:298:18)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2016-10-05 11:50:39] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'true'.
[2016-10-05 11:50:39] Initial is locked request finished.

http://xxx.xxx.xxx.xxx:yyyy/lockState?token=yourtoken&nukiId=yournukiid --> works fine...

THX

**Comment by kingwings81** [comment]
This is my config.json

"platform": "NukiBridge",
            "bridge_url": "192.168.X.XXX:8080",
            "api_token": "XXXXXX",
            "request_timeout_lockstate": 5000,
            "request_timeout_lockaction": 30000,
            "cache_directory": "./.node-persist/storage",
            "webhook_port": 51827,
            "lock_state_mode": 0,
            "locks": [{
                "id": "XXXXXX",
                "name": "Sicherheitsschloss",
                "lock_action": "2",
                "unlock_action": "1",
                "priority": 1

**Comment by benzman81** [comment]
Please add the protocol "http://" to your "bridge_url" and check if it works. If so, I will add documentation or code for it.

**Comment by kingwings81** [comment]
THX - worked for me. Tried this yesterday but there I had other problems and today I forgot to try this again…

**Comment by benzman81** [comment]
Fixed in code. You now do not need the prepend the protocol anymore.
