### ISSUE TITLE
Homebridge shutdown because of bridge was not reachable 

### ISSUE THREAD

**Issue by DJay-X** [benzman81/homebridge-nukiio#60]
Hey there.

Today I had to unplug the Nuki Bridge because I needed the socket. :)
However I forgot to plug it in again and after a while homebridge crashed. 
I think it's not the intention of the plugin that this "error" should shutdown the entire homebridge?

Maybe you find a way to prevent to do so. 

Thanks in advance for your consideration. 

```
[2020-7-30 21:15:29] [NukiBridge] Request to Nuki bridge 'http://192.168.xxx.xx' finished with status code '-1' and body 'undefined'. Error: connect EHOSTUNREACH 192.168.xxx.xx:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
 {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.xxx.xx',
  port: 80
}
[2020-7-30 21:15:29] Error: Request for webhooks failed: Error: connect EHOSTUNREACH 192.168.xxx.xx:80
    at NukiBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:129:13)
    at NukiBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:389:7)
    at self.callback (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:327:22)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-7-30 21:15:29] Got SIGTERM, shutting down Homebridge...
```

**Comment by DJay-X** [comment]
Not experienced this issue since a while. I close and in case of ongoing problem I will reopen.
Thanks.
