### ISSUE TITLE
Got SIGTERM, shutting down Homebridge...

### ISSUE THREAD

**Issue by DJay-X** [benzman81/homebridge-nukiio#72]
@benzman81 I hope you are well.

This morning I found my homebridge shut down. 
In the log I only could find Nuki which maybe caused the problem.

The Plugin probably shouldn't shutdown the entire homebridge because of a Bridge/Connection problem.

Or do you think it's something else?

Thanks for you time. 

```
[30.12.2020, 08:49:51] [NukiBridge] Request to Nuki bridge 'http://xxx.xxx.xxx.xx' finished with status code '-1' and body 'undefined'. Error: connect EHOSTUNREACH xxx.xxx.xxx.xx:xxxx
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
 {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: 'xxx.xxx.xxx.xx',
  port: xxxx
}
[30.12.2020, 08:49:51] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'true'.
[30.12.2020, 08:49:51] [NukiBridge] Initial is locked request finished.
[30.12.2020, 08:49:51] [NukiBridge] Send request to Nuki bridge 'http://xxx.xxx.xxx.xx' on '/callback/list' with '{"token":"xxxxxx"}'.
[30.12.2020, 08:49:51] [Feinstaubsensor] Could not get sensor data: Error: getaddrinfo ENOTFOUND feinstaubsensor-16493.local
[30.12.2020, 08:49:53] [cmdSwitch2] Failed to determine iMac Bildschirmschoner state.
[30.12.2020, 08:49:53] [cmdSwitch2] ssh: connect to host xxx.xxx.xxx.xx port xx: No route to host

[30.12.2020, 08:49:54] [NukiBridge] Request to Nuki bridge 'http://xxx.xxx.xxx.xx' finished with status code '-1' and body 'undefined'. Error: connect EHOSTUNREACH 1xxx.xxx.xxx.xx:xxxx
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
 {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: 'xxx.xxx.xxx.xx',
  port: xxxx
}
[30.12.2020, 08:49:54] Error: Request for webhooks failed: Error: connect EHOSTUNREACH xxx.xxx.xxx.xx:xxxx
    at NukiBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:132:13)
    at NukiBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:392:7)
    at self.callback (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:327:22)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

[30.12.2020, 08:49:54] Got SIGTERM, shutting down Homebridge...
```

**Comment by benzman81** [comment]
Sorry for late response. This must be an error on startup. All other calls should not kill Homebridge. On startup it is required to register the callback listener in the Nuki bridge and this is intended to fail as all other functionality relies on a correct state. If you have a suggestion or idea besides polling, feel free to add it here or create a pull request.
