### ISSUE TITLE
Error after restarting the Homebridge

### ISSUE THREAD

**Issue by Lars83** [benzman81/homebridge-nukiio#84]
Hello everyone, when I restart my Homebridge, I always get this error and the Homebridge keeps restarting.

After the second or third start, it will run.

Is it normal that it comes when you restart?

`  [11/10/2021, 22:14:29] [NukiBridge] Request to Nuki bridge 'http://192.168.0.187:8080' finished with status code '200' and body '{"mode": 2, "state": 3, "stateName": "unlocked", "batteryCritical": false, "batteryCharging": false, "batteryChargeState": 28, "doorsensorState": 2, "doorsensorStateName": "door closed", "success": true}'. null
[11/10/2021, 22:14:29] [NukiBridge] Lock state is isLocked = 'false' (Nuki state '3' ) with battery critical = 'false', battery charging = 'false', battery charge state = '28', contactClosed = 'true' and mode = '2'
[11/10/2021, 22:14:29] [NukiBridge] Initial is locked request finished.
[11/10/2021, 22:14:29] [NukiBridge] Send request to Nuki bridge 'http://192.168.0.187:8080' on '/callback/list' with '{"token":"XmjeUQ"}'.
[11/10/2021, 22:14:30] [NukiBridge] Request to Nuki bridge 'http://192.168.0.187:8080' finished with status code '503' and body 'HTTP 503 Unavailable'. null
[11/10/2021, 22:14:30] Error: Request for webhooks failed: Error: Request to Nuki bridge was not succesful. (statusCode=503, nukiUnsuccessfulError=false, retryableError=true)
    at NukiBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:134:13)
    at NukiBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:400:7)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[11/10/2021, 22:14:30] Got SIGTERM, shutting down Homebridge...`

**Comment by benzman81** [comment]
Fixed with 0.15.4.
