### ISSUE TITLE
Lock state mode problem

### ISSUE THREAD

**Issue by tobihoby** [benzman81/homebridge-nukiio#95]
Hallo,

für eine bessere HB Performance wollte ich den lock state mode von 3 auf 2 setzen.
Habe als webhook Server die IP der Homebridge eingetragen, den Port habe ich auf Default gelassen (ist laut netstat auch frei).

Bekomme dann das Plugin aber nicht mehr zum Laufen:

[30/12/2022, 10:12:24] [homebridge-nukiio] Loaded homebridge-nukiio v0.16.0 child bridge successfully
[30/12/2022, 10:12:24] Loaded 0 cached accessories from cachedAccessories.0E457FB5E4CC.
[30/12/2022, 10:12:24] [homebridge-nukiio] Initializing Nuki bridge 'http://192.168.0.236:8080'...
[30/12/2022, 10:12:24] [homebridge-nukiio] Started server for webhooks on port '51827'.
[30/12/2022, 10:12:24] [homebridge-nukiio] Adding webhook for plugin to bridge...
[30/12/2022, 10:12:24] [homebridge-nukiio] Initialized Nuki bridge.
[30/12/2022, 10:12:24] Initializing platform accessory 'Haustür'...
[30/12/2022, 10:12:24] Initializing platform accessory 'Garagentür'...
[30/12/2022, 10:12:24] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-nukiio) is running on port 44506.
[30/12/2022, 10:12:24] [homebridge-nukiio] Send request to Nuki bridge 'http://192.168.0.236:8080' on '/callback/list' with '{"token":"OKUiXg"}'.
[30/12/2022, 10:12:24] [homebridge-nukiio] Request to Nuki bridge 'http://192.168.0.236:8080' finished with status code '200' and body '{"callbacks": [{"id": 0, "url": "http://192.168.0.99:51827/"},{"id": 1, "url": "http://192.168.0.98:38527/notify/6109ADB3"},{"id": 2, "url": "undefined"}]}'. null
[30/12/2022, 10:12:24] [homebridge-nukiio] Send request to Nuki bridge 'http://192.168.0.236:8080' on '/callback/add' with '{"url":"http://192.168.0.98:51827/","token":"OKUiXg"}'.
[30/12/2022, 10:12:24] [homebridge-nukiio] Request to Nuki bridge 'http://192.168.0.236:8080' finished with status code '200' and body '{"success": false, "message": "too many callbacks registered"}'. null

/var/lib/homebridge/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:207
            throw new Error("Adding webhook failed after retrying multiple times: " + err);
                  ^
Error: Adding webhook failed after retrying multiple times: Error: Request to Nuki bridge was not succesful. (statusCode=200, nukiUnsuccessfulError=true, retryableError=true)
    at NukiBridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:207:19)
    at NukiBridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nukiio/src/nuki/NukiBridge.js:427:11)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-nukiio/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nukiio/node_modules/request/request.js:1157:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nukiio/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
[30/12/2022, 10:12:24] [homebridge-nukiio] Child bridge process ended
[30/12/2022, 10:12:24] [homebridge-nukiio] Process Ended. Code: 1, Signal: null

Vielleicht jemand eine Idee, woran es liegen könnte?
Danke

Gruß
Tobi

**Comment by tobihoby** [comment]
ah ich sehe glaub ich woran es liegt:
"too many callbacks registered"

Wie bekomme ich das denn gelöst?
In einem anderen Post habe ich etwas von einem NB Befehl gelesen, den gibt es hier aber wohl nicht.

**Comment by tobihoby** [comment]
Lösung selbst gefunden:

http://Nuki-Bridge:8080/callback/remove?token=yourtoken&id=0
http://Nuki-Bridge:8080/callback/remove?token=yourtoken&id=1
http://Nuki-Bridge:8080/callback/remove?token=yourtoken&id=2

**Comment by benzman81** [comment]
👍
